version: '2'
services:
 db:
  image: mongo:3.4
 backend:
  image: node:8.1
  volumes: 
   - ./backend:/backend
  ports: 
   - 3003:3003
  command: bash -c "cd /backend && npm i && npm run dev"
  #command: bash -c "cd /backend && npm i && npm run production backend"
 frontend:
  image: nginx:1.13
  volumes: 
   - ./frontend/public:/usr/share/nginx/html/
  ports: 
   - 4000:80